<a href="https://colab.research.google.com/github/danielduartt/POO-Python/blob/main/1_Criando_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#**Resumo do arquivo 'Saindo do Zero em Numpy' :**
*  Criando matrizes




In [ ]:
#Criando matriz:
arr = np.array([1, 2, 3])
#Matriz de zeros com shape específico:
arr2 = np.zeros(shape = (2, 3, 2))
#Matriz de valores iguais a 1 inteiros:
arr3 = np.ones(shape = (2, 3), dtype = np.int32) #2 Linhas, 3 Colunas
#Criar números específicos ( tipo a função range ):
arr4 = np.arange(start = 1, stop = 11, step = 1) #1 até 10 pulando de 1 em 1
#Criando um array linear
arr5 = np.linspace(start = 0, stop = 100, num = 20, endpoint = False, retstep = False)
#Bastante coisa nesse..., o start é padrão, bem como o stop
#Num = número de elementos entre 0, 100
#endpoint = False => não considera o 100 no conjunto estudado [0, 100[
#endpoint = True => considera o 100 [0, 100]
#restep = diferença entre cada valor

#**Criando um array de tipo específico:**



In [ ]:
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]


#**Mudando o tipo de um Array:**

In [ ]:
mt = np.array([1.4, 3.2, -5.3, 0.42, 4.9999])
print(type(mt[0]))
#Mudando para tipo inteiro 32 bits
mt = mt.astype(np.int32)
print(type(mt[0]))


<class 'numpy.float64'>
<class 'numpy.int32'>


#**Criando matriz de n dimensões:**

In [ ]:
mt = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int32)
print(mt)

[[1 2 3]
 [4 5 6]]


#**Criando arrays tipificado:**

In [ ]:
'''
empty = np.empty([3,2], dtype = np.int32) #=> não necessariamente é vazio, não vai ser é inicializado
zeros = np.zeros([4,3])
ones = np.onez([5,7])
'''
# Matriz Identidade
identidade = np.eye(5)
print(identidade)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#**Matrizes com valores aleatório**


In [ ]:
#Valores aleatórios usando o random
ale = np.random.random((3,5)) #3 Linhas, 5 Colunas
print(ale)

#Distribuição normal
print("~"*60)
ale2 = np.random.randn((5))
print(ale2)

#Valores aleatório 3 X 4
print("~"*60)
ale3 = (10 * np.random.random((3, 4))) #produto escalar
print(ale3)

#Outra forma de criar uma matriz aleatória
print("~"*60)
from numpy.random import default_rng
rng = default_rng()
random = rng.random(3)
print(random)
print("~"*60)
random2 = rng.integers(10, size = (2, 4), endpoint = True) #valroes inteiros entre 0 e 2 [0,10[ com o endpoint = False
#Usando o endpoint = True => [0 , 10], o 10 entra no conjunto criado de valores para a matriz
print(random2)


[[0.76075163 0.65386604 0.78613414 0.37673282 0.11242046]
 [0.12346895 0.02611977 0.24649215 0.60045258 0.83643938]
 [0.89208568 0.66554976 0.23036008 0.1888548  0.10004466]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[-1.54928258 -0.16223803  0.25883481  0.43053853  0.10345805]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0.77929498 9.58238176 5.96599864 0.39455769]
 [0.40439485 7.40469911 1.36403421 0.8008245 ]
 [1.35080263 0.42009682 6.13405841 0.53664641]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0.9040228  0.87205385 0.30015204]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 9  6  5 10]
 [10  2  6  4]]
